/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"


@interface Doctor : NSObject <TBase, NSCoding> {
  NSString * __clave;
  NSString * __nombre;
  NSString * __direccion;
  NSString * __especialidad;
  NSString * __telefono;
  NSString * __foto;

  BOOL __clave_isset;
  BOOL __nombre_isset;
  BOOL __direccion_isset;
  BOOL __especialidad_isset;
  BOOL __telefono_isset;
  BOOL __foto_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=clave, setter=setClave:) NSString * clave;
@property (nonatomic, retain, getter=nombre, setter=setNombre:) NSString * nombre;
@property (nonatomic, retain, getter=direccion, setter=setDireccion:) NSString * direccion;
@property (nonatomic, retain, getter=especialidad, setter=setEspecialidad:) NSString * especialidad;
@property (nonatomic, retain, getter=telefono, setter=setTelefono:) NSString * telefono;
@property (nonatomic, retain, getter=foto, setter=setFoto:) NSString * foto;
#endif

- (id) init;
- (id) initWithClave: (NSString *) clave nombre: (NSString *) nombre direccion: (NSString *) direccion especialidad: (NSString *) especialidad telefono: (NSString *) telefono foto: (NSString *) foto;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) clave;
- (void) setClave: (NSString *) clave;
#endif
- (BOOL) claveIsSet;

#if !__has_feature(objc_arc)
- (NSString *) nombre;
- (void) setNombre: (NSString *) nombre;
#endif
- (BOOL) nombreIsSet;

#if !__has_feature(objc_arc)
- (NSString *) direccion;
- (void) setDireccion: (NSString *) direccion;
#endif
- (BOOL) direccionIsSet;

#if !__has_feature(objc_arc)
- (NSString *) especialidad;
- (void) setEspecialidad: (NSString *) especialidad;
#endif
- (BOOL) especialidadIsSet;

#if !__has_feature(objc_arc)
- (NSString *) telefono;
- (void) setTelefono: (NSString *) telefono;
#endif
- (BOOL) telefonoIsSet;

#if !__has_feature(objc_arc)
- (NSString *) foto;
- (void) setFoto: (NSString *) foto;
#endif
- (BOOL) fotoIsSet;

@end

@interface AnalisisClinico : NSObject <TBase, NSCoding> {
  NSString * __clave;
  NSString * __tipo;
  NSString * __descripcion;

  BOOL __clave_isset;
  BOOL __tipo_isset;
  BOOL __descripcion_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=clave, setter=setClave:) NSString * clave;
@property (nonatomic, retain, getter=tipo, setter=setTipo:) NSString * tipo;
@property (nonatomic, retain, getter=descripcion, setter=setDescripcion:) NSString * descripcion;
#endif

- (id) init;
- (id) initWithClave: (NSString *) clave tipo: (NSString *) tipo descripcion: (NSString *) descripcion;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) clave;
- (void) setClave: (NSString *) clave;
#endif
- (BOOL) claveIsSet;

#if !__has_feature(objc_arc)
- (NSString *) tipo;
- (void) setTipo: (NSString *) tipo;
#endif
- (BOOL) tipoIsSet;

#if !__has_feature(objc_arc)
- (NSString *) descripcion;
- (void) setDescripcion: (NSString *) descripcion;
#endif
- (BOOL) descripcionIsSet;

@end

@interface Atiende : NSObject <TBase, NSCoding> {
  NSString * __claveDoctor;
  NSString * __clavePaciente;
  NSString * __fecha;
  NSString * __tratamiento;
  NSString * __diagnostico;
  NSString * __fotoDoctor;
  NSString * __fotoPaciente;

  BOOL __claveDoctor_isset;
  BOOL __clavePaciente_isset;
  BOOL __fecha_isset;
  BOOL __tratamiento_isset;
  BOOL __diagnostico_isset;
  BOOL __fotoDoctor_isset;
  BOOL __fotoPaciente_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=claveDoctor, setter=setClaveDoctor:) NSString * claveDoctor;
@property (nonatomic, retain, getter=clavePaciente, setter=setClavePaciente:) NSString * clavePaciente;
@property (nonatomic, retain, getter=fecha, setter=setFecha:) NSString * fecha;
@property (nonatomic, retain, getter=tratamiento, setter=setTratamiento:) NSString * tratamiento;
@property (nonatomic, retain, getter=diagnostico, setter=setDiagnostico:) NSString * diagnostico;
@property (nonatomic, retain, getter=fotoDoctor, setter=setFotoDoctor:) NSString * fotoDoctor;
@property (nonatomic, retain, getter=fotoPaciente, setter=setFotoPaciente:) NSString * fotoPaciente;
#endif

- (id) init;
- (id) initWithClaveDoctor: (NSString *) claveDoctor clavePaciente: (NSString *) clavePaciente fecha: (NSString *) fecha tratamiento: (NSString *) tratamiento diagnostico: (NSString *) diagnostico fotoDoctor: (NSString *) fotoDoctor fotoPaciente: (NSString *) fotoPaciente;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) claveDoctor;
- (void) setClaveDoctor: (NSString *) claveDoctor;
#endif
- (BOOL) claveDoctorIsSet;

#if !__has_feature(objc_arc)
- (NSString *) clavePaciente;
- (void) setClavePaciente: (NSString *) clavePaciente;
#endif
- (BOOL) clavePacienteIsSet;

#if !__has_feature(objc_arc)
- (NSString *) fecha;
- (void) setFecha: (NSString *) fecha;
#endif
- (BOOL) fechaIsSet;

#if !__has_feature(objc_arc)
- (NSString *) tratamiento;
- (void) setTratamiento: (NSString *) tratamiento;
#endif
- (BOOL) tratamientoIsSet;

#if !__has_feature(objc_arc)
- (NSString *) diagnostico;
- (void) setDiagnostico: (NSString *) diagnostico;
#endif
- (BOOL) diagnosticoIsSet;

#if !__has_feature(objc_arc)
- (NSString *) fotoDoctor;
- (void) setFotoDoctor: (NSString *) fotoDoctor;
#endif
- (BOOL) fotoDoctorIsSet;

#if !__has_feature(objc_arc)
- (NSString *) fotoPaciente;
- (void) setFotoPaciente: (NSString *) fotoPaciente;
#endif
- (BOOL) fotoPacienteIsSet;

@end

@interface Paciente : NSObject <TBase, NSCoding> {
  NSString * __clave;
  NSString * __nombre;
  NSString * __direccion;
  NSString * __telefono;
  NSString * __foto;

  BOOL __clave_isset;
  BOOL __nombre_isset;
  BOOL __direccion_isset;
  BOOL __telefono_isset;
  BOOL __foto_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=clave, setter=setClave:) NSString * clave;
@property (nonatomic, retain, getter=nombre, setter=setNombre:) NSString * nombre;
@property (nonatomic, retain, getter=direccion, setter=setDireccion:) NSString * direccion;
@property (nonatomic, retain, getter=telefono, setter=setTelefono:) NSString * telefono;
@property (nonatomic, retain, getter=foto, setter=setFoto:) NSString * foto;
#endif

- (id) init;
- (id) initWithClave: (NSString *) clave nombre: (NSString *) nombre direccion: (NSString *) direccion telefono: (NSString *) telefono foto: (NSString *) foto;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) clave;
- (void) setClave: (NSString *) clave;
#endif
- (BOOL) claveIsSet;

#if !__has_feature(objc_arc)
- (NSString *) nombre;
- (void) setNombre: (NSString *) nombre;
#endif
- (BOOL) nombreIsSet;

#if !__has_feature(objc_arc)
- (NSString *) direccion;
- (void) setDireccion: (NSString *) direccion;
#endif
- (BOOL) direccionIsSet;

#if !__has_feature(objc_arc)
- (NSString *) telefono;
- (void) setTelefono: (NSString *) telefono;
#endif
- (BOOL) telefonoIsSet;

#if !__has_feature(objc_arc)
- (NSString *) foto;
- (void) setFoto: (NSString *) foto;
#endif
- (BOOL) fotoIsSet;

@end

@interface SeRealiza : NSObject <TBase, NSCoding> {
  NSString * __claveAnalisis;
  NSString * __clavePaciente;
  NSString * __fechaAplic;
  NSString * __fechaEntrega;
  NSString * __fotoPaciente;

  BOOL __claveAnalisis_isset;
  BOOL __clavePaciente_isset;
  BOOL __fechaAplic_isset;
  BOOL __fechaEntrega_isset;
  BOOL __fotoPaciente_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=claveAnalisis, setter=setClaveAnalisis:) NSString * claveAnalisis;
@property (nonatomic, retain, getter=clavePaciente, setter=setClavePaciente:) NSString * clavePaciente;
@property (nonatomic, retain, getter=fechaAplic, setter=setFechaAplic:) NSString * fechaAplic;
@property (nonatomic, retain, getter=fechaEntrega, setter=setFechaEntrega:) NSString * fechaEntrega;
@property (nonatomic, retain, getter=fotoPaciente, setter=setFotoPaciente:) NSString * fotoPaciente;
#endif

- (id) init;
- (id) initWithClaveAnalisis: (NSString *) claveAnalisis clavePaciente: (NSString *) clavePaciente fechaAplic: (NSString *) fechaAplic fechaEntrega: (NSString *) fechaEntrega fotoPaciente: (NSString *) fotoPaciente;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) claveAnalisis;
- (void) setClaveAnalisis: (NSString *) claveAnalisis;
#endif
- (BOOL) claveAnalisisIsSet;

#if !__has_feature(objc_arc)
- (NSString *) clavePaciente;
- (void) setClavePaciente: (NSString *) clavePaciente;
#endif
- (BOOL) clavePacienteIsSet;

#if !__has_feature(objc_arc)
- (NSString *) fechaAplic;
- (void) setFechaAplic: (NSString *) fechaAplic;
#endif
- (BOOL) fechaAplicIsSet;

#if !__has_feature(objc_arc)
- (NSString *) fechaEntrega;
- (void) setFechaEntrega: (NSString *) fechaEntrega;
#endif
- (BOOL) fechaEntregaIsSet;

#if !__has_feature(objc_arc)
- (NSString *) fotoPaciente;
- (void) setFotoPaciente: (NSString *) fotoPaciente;
#endif
- (BOOL) fotoPacienteIsSet;

@end

@interface ReporteAnalisisPaciente : NSObject <TBase, NSCoding> {
  NSString * __clavePaciente;
  NSString * __claveAnalisis;
  NSString * __fechaAplic;
  NSString * __nombrePaciente;
  NSString * __fechaEntrega;
  NSString * __tipo;
  NSString * __descripcion;
  NSString * __fotoPaciente;

  BOOL __clavePaciente_isset;
  BOOL __claveAnalisis_isset;
  BOOL __fechaAplic_isset;
  BOOL __nombrePaciente_isset;
  BOOL __fechaEntrega_isset;
  BOOL __tipo_isset;
  BOOL __descripcion_isset;
  BOOL __fotoPaciente_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=clavePaciente, setter=setClavePaciente:) NSString * clavePaciente;
@property (nonatomic, retain, getter=claveAnalisis, setter=setClaveAnalisis:) NSString * claveAnalisis;
@property (nonatomic, retain, getter=fechaAplic, setter=setFechaAplic:) NSString * fechaAplic;
@property (nonatomic, retain, getter=nombrePaciente, setter=setNombrePaciente:) NSString * nombrePaciente;
@property (nonatomic, retain, getter=fechaEntrega, setter=setFechaEntrega:) NSString * fechaEntrega;
@property (nonatomic, retain, getter=tipo, setter=setTipo:) NSString * tipo;
@property (nonatomic, retain, getter=descripcion, setter=setDescripcion:) NSString * descripcion;
@property (nonatomic, retain, getter=fotoPaciente, setter=setFotoPaciente:) NSString * fotoPaciente;
#endif

- (id) init;
- (id) initWithClavePaciente: (NSString *) clavePaciente claveAnalisis: (NSString *) claveAnalisis fechaAplic: (NSString *) fechaAplic nombrePaciente: (NSString *) nombrePaciente fechaEntrega: (NSString *) fechaEntrega tipo: (NSString *) tipo descripcion: (NSString *) descripcion fotoPaciente: (NSString *) fotoPaciente;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) clavePaciente;
- (void) setClavePaciente: (NSString *) clavePaciente;
#endif
- (BOOL) clavePacienteIsSet;

#if !__has_feature(objc_arc)
- (NSString *) claveAnalisis;
- (void) setClaveAnalisis: (NSString *) claveAnalisis;
#endif
- (BOOL) claveAnalisisIsSet;

#if !__has_feature(objc_arc)
- (NSString *) fechaAplic;
- (void) setFechaAplic: (NSString *) fechaAplic;
#endif
- (BOOL) fechaAplicIsSet;

#if !__has_feature(objc_arc)
- (NSString *) nombrePaciente;
- (void) setNombrePaciente: (NSString *) nombrePaciente;
#endif
- (BOOL) nombrePacienteIsSet;

#if !__has_feature(objc_arc)
- (NSString *) fechaEntrega;
- (void) setFechaEntrega: (NSString *) fechaEntrega;
#endif
- (BOOL) fechaEntregaIsSet;

#if !__has_feature(objc_arc)
- (NSString *) tipo;
- (void) setTipo: (NSString *) tipo;
#endif
- (BOOL) tipoIsSet;

#if !__has_feature(objc_arc)
- (NSString *) descripcion;
- (void) setDescripcion: (NSString *) descripcion;
#endif
- (BOOL) descripcionIsSet;

#if !__has_feature(objc_arc)
- (NSString *) fotoPaciente;
- (void) setFotoPaciente: (NSString *) fotoPaciente;
#endif
- (BOOL) fotoPacienteIsSet;

@end

@interface ReporteDoctoresPaciente : NSObject <TBase, NSCoding> {
  NSString * __clavePaciente;
  NSString * __claveDoctor;
  NSString * __nombrePaciente;
  NSString * __nombreDoctor;
  NSString * __tratamiento;
  NSString * __diagnostico;
  NSString * __fecha;
  NSString * __fotoDoctor;
  NSString * __fotoPaciente;

  BOOL __clavePaciente_isset;
  BOOL __claveDoctor_isset;
  BOOL __nombrePaciente_isset;
  BOOL __nombreDoctor_isset;
  BOOL __tratamiento_isset;
  BOOL __diagnostico_isset;
  BOOL __fecha_isset;
  BOOL __fotoDoctor_isset;
  BOOL __fotoPaciente_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=clavePaciente, setter=setClavePaciente:) NSString * clavePaciente;
@property (nonatomic, retain, getter=claveDoctor, setter=setClaveDoctor:) NSString * claveDoctor;
@property (nonatomic, retain, getter=nombrePaciente, setter=setNombrePaciente:) NSString * nombrePaciente;
@property (nonatomic, retain, getter=nombreDoctor, setter=setNombreDoctor:) NSString * nombreDoctor;
@property (nonatomic, retain, getter=tratamiento, setter=setTratamiento:) NSString * tratamiento;
@property (nonatomic, retain, getter=diagnostico, setter=setDiagnostico:) NSString * diagnostico;
@property (nonatomic, retain, getter=fecha, setter=setFecha:) NSString * fecha;
@property (nonatomic, retain, getter=fotoDoctor, setter=setFotoDoctor:) NSString * fotoDoctor;
@property (nonatomic, retain, getter=fotoPaciente, setter=setFotoPaciente:) NSString * fotoPaciente;
#endif

- (id) init;
- (id) initWithClavePaciente: (NSString *) clavePaciente claveDoctor: (NSString *) claveDoctor nombrePaciente: (NSString *) nombrePaciente nombreDoctor: (NSString *) nombreDoctor tratamiento: (NSString *) tratamiento diagnostico: (NSString *) diagnostico fecha: (NSString *) fecha fotoDoctor: (NSString *) fotoDoctor fotoPaciente: (NSString *) fotoPaciente;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) clavePaciente;
- (void) setClavePaciente: (NSString *) clavePaciente;
#endif
- (BOOL) clavePacienteIsSet;

#if !__has_feature(objc_arc)
- (NSString *) claveDoctor;
- (void) setClaveDoctor: (NSString *) claveDoctor;
#endif
- (BOOL) claveDoctorIsSet;

#if !__has_feature(objc_arc)
- (NSString *) nombrePaciente;
- (void) setNombrePaciente: (NSString *) nombrePaciente;
#endif
- (BOOL) nombrePacienteIsSet;

#if !__has_feature(objc_arc)
- (NSString *) nombreDoctor;
- (void) setNombreDoctor: (NSString *) nombreDoctor;
#endif
- (BOOL) nombreDoctorIsSet;

#if !__has_feature(objc_arc)
- (NSString *) tratamiento;
- (void) setTratamiento: (NSString *) tratamiento;
#endif
- (BOOL) tratamientoIsSet;

#if !__has_feature(objc_arc)
- (NSString *) diagnostico;
- (void) setDiagnostico: (NSString *) diagnostico;
#endif
- (BOOL) diagnosticoIsSet;

#if !__has_feature(objc_arc)
- (NSString *) fecha;
- (void) setFecha: (NSString *) fecha;
#endif
- (BOOL) fechaIsSet;

#if !__has_feature(objc_arc)
- (NSString *) fotoDoctor;
- (void) setFotoDoctor: (NSString *) fotoDoctor;
#endif
- (BOOL) fotoDoctorIsSet;

#if !__has_feature(objc_arc)
- (NSString *) fotoPaciente;
- (void) setFotoPaciente: (NSString *) fotoPaciente;
#endif
- (BOOL) fotoPacienteIsSet;

@end

@interface ReportePacientesAnalisis : NSObject <TBase, NSCoding> {
  NSString * __clavePaciente;
  NSString * __claveAnalisis;
  NSString * __fechaAplic;
  NSString * __nombrePaciente;
  NSString * __fechaEntrega;
  NSString * __tipo;
  NSString * __descripcion;
  NSString * __fotoPaciente;

  BOOL __clavePaciente_isset;
  BOOL __claveAnalisis_isset;
  BOOL __fechaAplic_isset;
  BOOL __nombrePaciente_isset;
  BOOL __fechaEntrega_isset;
  BOOL __tipo_isset;
  BOOL __descripcion_isset;
  BOOL __fotoPaciente_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=clavePaciente, setter=setClavePaciente:) NSString * clavePaciente;
@property (nonatomic, retain, getter=claveAnalisis, setter=setClaveAnalisis:) NSString * claveAnalisis;
@property (nonatomic, retain, getter=fechaAplic, setter=setFechaAplic:) NSString * fechaAplic;
@property (nonatomic, retain, getter=nombrePaciente, setter=setNombrePaciente:) NSString * nombrePaciente;
@property (nonatomic, retain, getter=fechaEntrega, setter=setFechaEntrega:) NSString * fechaEntrega;
@property (nonatomic, retain, getter=tipo, setter=setTipo:) NSString * tipo;
@property (nonatomic, retain, getter=descripcion, setter=setDescripcion:) NSString * descripcion;
@property (nonatomic, retain, getter=fotoPaciente, setter=setFotoPaciente:) NSString * fotoPaciente;
#endif

- (id) init;
- (id) initWithClavePaciente: (NSString *) clavePaciente claveAnalisis: (NSString *) claveAnalisis fechaAplic: (NSString *) fechaAplic nombrePaciente: (NSString *) nombrePaciente fechaEntrega: (NSString *) fechaEntrega tipo: (NSString *) tipo descripcion: (NSString *) descripcion fotoPaciente: (NSString *) fotoPaciente;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) clavePaciente;
- (void) setClavePaciente: (NSString *) clavePaciente;
#endif
- (BOOL) clavePacienteIsSet;

#if !__has_feature(objc_arc)
- (NSString *) claveAnalisis;
- (void) setClaveAnalisis: (NSString *) claveAnalisis;
#endif
- (BOOL) claveAnalisisIsSet;

#if !__has_feature(objc_arc)
- (NSString *) fechaAplic;
- (void) setFechaAplic: (NSString *) fechaAplic;
#endif
- (BOOL) fechaAplicIsSet;

#if !__has_feature(objc_arc)
- (NSString *) nombrePaciente;
- (void) setNombrePaciente: (NSString *) nombrePaciente;
#endif
- (BOOL) nombrePacienteIsSet;

#if !__has_feature(objc_arc)
- (NSString *) fechaEntrega;
- (void) setFechaEntrega: (NSString *) fechaEntrega;
#endif
- (BOOL) fechaEntregaIsSet;

#if !__has_feature(objc_arc)
- (NSString *) tipo;
- (void) setTipo: (NSString *) tipo;
#endif
- (BOOL) tipoIsSet;

#if !__has_feature(objc_arc)
- (NSString *) descripcion;
- (void) setDescripcion: (NSString *) descripcion;
#endif
- (BOOL) descripcionIsSet;

#if !__has_feature(objc_arc)
- (NSString *) fotoPaciente;
- (void) setFotoPaciente: (NSString *) fotoPaciente;
#endif
- (BOOL) fotoPacienteIsSet;

@end

@interface ReportePacientesDoctor : NSObject <TBase, NSCoding> {
  NSString * __clavePaciente;
  NSString * __claveDoctor;
  NSString * __nombrePaciente;
  NSString * __nombreDoctor;
  NSString * __tratamiento;
  NSString * __diagnostico;
  NSString * __fecha;
  NSString * __fotoDoctor;
  NSString * __fotoPaciente;

  BOOL __clavePaciente_isset;
  BOOL __claveDoctor_isset;
  BOOL __nombrePaciente_isset;
  BOOL __nombreDoctor_isset;
  BOOL __tratamiento_isset;
  BOOL __diagnostico_isset;
  BOOL __fecha_isset;
  BOOL __fotoDoctor_isset;
  BOOL __fotoPaciente_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=clavePaciente, setter=setClavePaciente:) NSString * clavePaciente;
@property (nonatomic, retain, getter=claveDoctor, setter=setClaveDoctor:) NSString * claveDoctor;
@property (nonatomic, retain, getter=nombrePaciente, setter=setNombrePaciente:) NSString * nombrePaciente;
@property (nonatomic, retain, getter=nombreDoctor, setter=setNombreDoctor:) NSString * nombreDoctor;
@property (nonatomic, retain, getter=tratamiento, setter=setTratamiento:) NSString * tratamiento;
@property (nonatomic, retain, getter=diagnostico, setter=setDiagnostico:) NSString * diagnostico;
@property (nonatomic, retain, getter=fecha, setter=setFecha:) NSString * fecha;
@property (nonatomic, retain, getter=fotoDoctor, setter=setFotoDoctor:) NSString * fotoDoctor;
@property (nonatomic, retain, getter=fotoPaciente, setter=setFotoPaciente:) NSString * fotoPaciente;
#endif

- (id) init;
- (id) initWithClavePaciente: (NSString *) clavePaciente claveDoctor: (NSString *) claveDoctor nombrePaciente: (NSString *) nombrePaciente nombreDoctor: (NSString *) nombreDoctor tratamiento: (NSString *) tratamiento diagnostico: (NSString *) diagnostico fecha: (NSString *) fecha fotoDoctor: (NSString *) fotoDoctor fotoPaciente: (NSString *) fotoPaciente;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) clavePaciente;
- (void) setClavePaciente: (NSString *) clavePaciente;
#endif
- (BOOL) clavePacienteIsSet;

#if !__has_feature(objc_arc)
- (NSString *) claveDoctor;
- (void) setClaveDoctor: (NSString *) claveDoctor;
#endif
- (BOOL) claveDoctorIsSet;

#if !__has_feature(objc_arc)
- (NSString *) nombrePaciente;
- (void) setNombrePaciente: (NSString *) nombrePaciente;
#endif
- (BOOL) nombrePacienteIsSet;

#if !__has_feature(objc_arc)
- (NSString *) nombreDoctor;
- (void) setNombreDoctor: (NSString *) nombreDoctor;
#endif
- (BOOL) nombreDoctorIsSet;

#if !__has_feature(objc_arc)
- (NSString *) tratamiento;
- (void) setTratamiento: (NSString *) tratamiento;
#endif
- (BOOL) tratamientoIsSet;

#if !__has_feature(objc_arc)
- (NSString *) diagnostico;
- (void) setDiagnostico: (NSString *) diagnostico;
#endif
- (BOOL) diagnosticoIsSet;

#if !__has_feature(objc_arc)
- (NSString *) fecha;
- (void) setFecha: (NSString *) fecha;
#endif
- (BOOL) fechaIsSet;

#if !__has_feature(objc_arc)
- (NSString *) fotoDoctor;
- (void) setFotoDoctor: (NSString *) fotoDoctor;
#endif
- (BOOL) fotoDoctorIsSet;

#if !__has_feature(objc_arc)
- (NSString *) fotoPaciente;
- (void) setFotoPaciente: (NSString *) fotoPaciente;
#endif
- (BOOL) fotoPacienteIsSet;

@end

@protocol Actions <NSObject>
- (BOOL) actualizarAnalisis: (AnalisisClinico *) analisis;  // throws TException
- (BOOL) actualizarDoctor: (Doctor *) doctor;  // throws TException
- (BOOL) actualizarPaciente: (Paciente *) paciente;  // throws TException
- (BOOL) borrarAnalisis: (NSString *) claveAnalisis;  // throws TException
- (BOOL) borrarDoctor: (NSString *) claveDoctor;  // throws TException
- (BOOL) borrarPaciente: (NSString *) clavePaciente;  // throws TException
- (BOOL) capturarAnalisis: (AnalisisClinico *) analisis;  // throws TException
- (BOOL) capturarDoctor: (Doctor *) doctor;  // throws TException
- (BOOL) capturarPaciente: (Paciente *) paciente;  // throws TException
- (BOOL) capturarAtiende: (Atiende *) atiende;  // throws TException
- (BOOL) capturarSeRealiza: (SeRealiza *) seRealiza;  // throws TException
- (NSMutableArray *) consultarAnalisis;  // throws TException
- (NSMutableArray *) consultarAtiende;  // throws TException
- (NSMutableArray *) consultarDoctores;  // throws TException
- (NSMutableArray *) consultarPacientes;  // throws TException
- (NSMutableArray *) consultarSeRealiza;  // throws TException
- (AnalisisClinico *) consultarAnalisisClave: (NSString *) clave;  // throws TException
- (Paciente *) consultarPacienteClave: (NSString *) clave;  // throws TException
- (Doctor *) consultarDoctorClave: (NSString *) clave;  // throws TException
- (NSMutableArray *) consultarAnalisisTipo: (NSString *) tipo;  // throws TException
- (NSMutableArray *) consultarDoctoresEspecialidad: (NSString *) especialidad;  // throws TException
- (NSMutableArray *) generarReporteAnalisisPaciente: (NSString *) clavePaciente;  // throws TException
- (NSMutableArray *) generarReportePacientesAnalisis: (NSString *) claveAnalisis;  // throws TException
- (NSMutableArray *) generarReporteDoctoresPaciente: (NSString *) clavePaciente;  // throws TException
- (NSMutableArray *) generarReportePacientesDoctor: (NSString *) claveDoctor;  // throws TException
@end

@interface ActionsClient : NSObject <Actions> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface ActionsProcessor : NSObject <TProcessor> {
  id <Actions> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithActions: (id <Actions>) service;
- (id<Actions>) service;
@end

@interface actionsConstants : NSObject {
}
@end
